name: Fx.Tabs
author: vincentbluff
category: InterFace
tags: [tabs]
current: 1.5
#docs: http://www.shaunfreeman.co.uk/content/article/page-MorphTabs
#demo: http://www.shaunfreeman.co.uk/content/article/page-MorphTabs#demo